/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    BreadcrumbNav: typeof import('./components/layout/BreadcrumbNav.vue')['default']
    Button: typeof import('primevue/button')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    IconPicker: typeof import('./components/project/IconPicker.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProjectCard: typeof import('./components/project/ProjectCard.vue')['default']
    ProjectColorPicker: typeof import('./components/project/ProjectColorPicker.vue')['default']
    ProjectStylePicker: typeof import('./components/project/ProjectStylePicker.vue')['default']
    RichTextEditor: typeof import('./components/common/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    TagSelector: typeof import('./components/task/TagSelector.vue')['default']
    TaskFieldRow: typeof import('./components/task/TaskFieldRow.vue')['default']
    UserAvatar: typeof import('./components/common/UserAvatar.vue')['default']
    UserMenu: typeof import('./components/layout/UserMenu.vue')['default']
  }
}
