/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    BreadcrumbNav: typeof import('./components/layout/BreadcrumbNav.vue')['default']
    IconPicker: typeof import('./components/project/IconPicker.vue')['default']
    ProjectColorPicker: typeof import('./components/project/ProjectColorPicker.vue')['default']
    ProjectStylePicker: typeof import('./components/project/ProjectStylePicker.vue')['default']
    RichTextEditor: typeof import('./components/common/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./components/common/UserAvatar.vue')['default']
    UserMenu: typeof import('./components/layout/UserMenu.vue')['default']
  }
}
